sudo: false
language: rust
cache: cargo
notifications:
  email: false
rust: nightly
env: RUST_BACKTRACE=1
addons:
  firefox: latest
  chrome: stable
before_script:
  # rust stuff
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - cargo install-update -a
  # wasm-pack
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
  # nvm
  - nvm install stable
  - nvm use stable
  - npm install
script:
  - commitlint-travis
  - npm run build
after_success:
  - npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/
